apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-ctr
  namespace: yinanli
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: docker.io/yinanli617/pyspark-operator:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: local:///pipelines/pyspark-job.py
  sparkVersion: "3.1.1"
  hadoopConf:
    "fs.gs.project.id": "kubeflow-yli"
    "fs.gs.system.bucket": "pyspark-yli"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/spark-sa.json"
  driver:
    cores: 1
    labels:
      version: 3.1.1
    secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: kubeflow-yli
    serviceAccount: spark-sa
  executor:
    instances: 3
    cores: 3
    labels:
      version: 3.1.1
    memory: "5g"
    secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: kubeflow-yli
